/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppListaRouteImport } from './routes/app.lista'
import { Route as AppPaletasRouteImport } from './routes/app.paletas'
import { Route as ApiPublicHotmartRouteImport } from './routes/api/public/hotmart'
import { Route as AppPassoNumeroRouteImport } from './routes/app.passo.$numero'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppListaRoute = AppListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => AppRoute,
} as any)
const AppPaletasRoute = AppPaletasRouteImport.update({
  id: '/paletas',
  path: '/paletas',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHotmartRoute = ApiPublicHotmartRouteImport.update({
  id: '/api/public/hotmart',
  path: '/api/public/hotmart',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPassoNumeroRoute = AppPassoNumeroRouteImport.update({
  id: '/passo/$numero',
  path: '/passo/$numero',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/lista': typeof AppListaRoute
  '/app/paletas': typeof AppPaletasRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hotmart': typeof ApiPublicHotmartRoute
  '/app/passo/$numero': typeof AppPassoNumeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/lista': typeof AppListaRoute
  '/app/paletas': typeof AppPaletasRoute
  '/app': typeof AppIndexRoute
  '/api/public/hotmart': typeof ApiPublicHotmartRoute
  '/app/passo/$numero': typeof AppPassoNumeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/lista': typeof AppListaRoute
  '/app/paletas': typeof AppPaletasRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hotmart': typeof ApiPublicHotmartRoute
  '/app/passo/$numero': typeof AppPassoNumeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/lista'
    | '/app/paletas'
    | '/app/'
    | '/api/public/hotmart'
    | '/app/passo/$numero'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/lista'
    | '/app/paletas'
    | '/app'
    | '/api/public/hotmart'
    | '/app/passo/$numero'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/lista'
    | '/app/paletas'
    | '/app/'
    | '/api/public/hotmart'
    | '/app/passo/$numero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHotmartRoute: typeof ApiPublicHotmartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lista': {
      id: '/app/lista'
      path: '/lista'
      fullPath: '/app/lista'
      preLoaderRoute: typeof AppListaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paletas': {
      id: '/app/paletas'
      path: '/paletas'
      fullPath: '/app/paletas'
      preLoaderRoute: typeof AppPaletasRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hotmart': {
      id: '/api/public/hotmart'
      path: '/api/public/hotmart'
      fullPath: '/api/public/hotmart'
      preLoaderRoute: typeof ApiPublicHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/passo/$numero': {
      id: '/app/passo/$numero'
      path: '/passo/$numero'
      fullPath: '/app/passo/$numero'
      preLoaderRoute: typeof AppPassoNumeroRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppListaRoute: typeof AppListaRoute
  AppPaletasRoute: typeof AppPaletasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPassoNumeroRoute: typeof AppPassoNumeroRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppListaRoute: AppListaRoute,
  AppPaletasRoute: AppPaletasRoute,
  AppIndexRoute: AppIndexRoute,
  AppPassoNumeroRoute: AppPassoNumeroRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHotmartRoute: ApiPublicHotmartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
